#version 430 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform readonly  image2D sat;
layout(rgba32f, binding = 1) uniform writeonly image2D dst;

uniform int r;

void main(void)
{
	const ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
	const ivec2 min_c = ivec2(-1);
	const ivec2 max_c = imageSize(sat) - ivec2(1);

	const ivec2 lt_c = clamp(uv + ivec2(-r-1, -r-1), min_c, max_c);
	const ivec2 rt_c = clamp(uv + ivec2(   r, -r-1), min_c, max_c);
	const ivec2 lb_c = clamp(uv + ivec2(-r-1,    r), min_c, max_c);
	const ivec2 rb_c = clamp(uv + ivec2(   r,    r), min_c, max_c);

	const vec4 lt = (lt_c.x == -1 || lt_c.y == -1) ? vec4(0.0) : imageLoad(sat, lt_c).rgba;
	const vec4 rt = (uv.y < r+1) ? vec4(0.0) : imageLoad(sat, rt_c).rgba;
	const vec4 lb = (uv.x < r+1) ? vec4(0.0) : imageLoad(sat, lb_c).rgba;
	const vec4 rb = imageLoad(sat, rb_c).rgba;

	vec4 color = rb + lt - rt - lb;
	color /= (rb_c - lt_c).x * (rb_c - lt_c).y;
	imageStore(dst, uv, color);
}