#version 460 core

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(rgba16f, binding = 0) uniform image2D U_tar;
layout(rgba8, binding = 1) uniform image2D U_tar_8;
layout(r16f, binding = 2) uniform image2D U_tar_r;

uniform vec4 color;
uniform int slot;

void main(){
	ivec2 uv = ivec2(gl_GlobalInvocationID.xy);

	switch(slot){
	case 0: imageStore(U_tar, uv, color); break;
	case 1: imageStore(U_tar_8, uv, color); break;
	case 2: imageStore(U_tar_r, uv, color); break;
	}
}