var hierarchy =
[
    [ "Application", "classApplication.html", null ],
    [ "ShadowSystem::AreaStruct", "structShadowSystem_1_1AreaStruct.html", null ],
    [ "Shaders::ArrayUni", "structShaders_1_1ArrayUni.html", null ],
    [ "AverageTime< _L >", "structAverageTime.html", null ],
    [ "TextEditor::Breakpoint", "structTextEditor_1_1Breakpoint.html", null ],
    [ "BufferElement", "structBufferElement.html", null ],
    [ "BufferLayout", "classBufferLayout.html", null ],
    [ "MeshData::ByteArray", "structMeshData_1_1ByteArray.html", null ],
    [ "CameraPushEvent", "structCameraPushEvent.html", null ],
    [ "CameraResizeEvent", "structCameraResizeEvent.html", null ],
    [ "CameraRotateEvent", "structCameraRotateEvent.html", null ],
    [ "CameraSlideEvent", "structCameraSlideEvent.html", null ],
    [ "CameraSpinEvent", "structCameraSpinEvent.html", null ],
    [ "CameraZoomEvent", "structCameraZoomEvent.html", null ],
    [ "Context", "classContext.html", null ],
    [ "ControllerManager", "classControllerManager.html", null ],
    [ "Controllers", "classControllers.html", [
      [ "CameraController", "classCameraController.html", null ],
      [ "ShaderController", "classShaderController.html", null ],
      [ "ViewportController", "classViewportController.html", null ]
    ] ],
    [ "TextEditor::Coordinates", "structTextEditor_1_1Coordinates.html", null ],
    [ "DebugMesh", "classDebugMesh.html", null ],
    [ "EditorContext", "classEditorContext.html", null ],
    [ "EventPool", "classEventPool.html", null ],
    [ "Events", "classEvents.html", null ],
    [ "std::false_type", null, [
      [ "is_not_vector< std::vector< T, C > >", "structis__not__vector_3_01std_1_1vector_3_01T_00_01C_01_4_01_4.html", null ]
    ] ],
    [ "FBPixel", "structFBPixel.html", null ],
    [ "FrameBuffer", "classFrameBuffer.html", null ],
    [ "FrameBufferResetEvent", "structFrameBufferResetEvent.html", null ],
    [ "GLBuffer", "classGLBuffer.html", [
      [ "IndexBuffer", "classIndexBuffer.html", null ],
      [ "StorageBuffer", "classStorageBuffer.html", null ],
      [ "UniformBuffer", "classUniformBuffer.html", null ],
      [ "VertexBuffer", "classVertexBuffer.html", null ]
    ] ],
    [ "TextEditor::Glyph", "structTextEditor_1_1Glyph.html", null ],
    [ "Shaders::ShaderUnit::hash_fn", "structShaders_1_1ShaderUnit_1_1hash__fn.html", null ],
    [ "TextEditor::Identifier", "structTextEditor_1_1Identifier.html", null ],
    [ "ImguiItem", "classImguiItem.html", [
      [ "UI::Button", "classUI_1_1Button.html", null ],
      [ "UI::OpaButton", "classUI_1_1OpaButton.html", null ],
      [ "UI::ParaInput", "classUI_1_1ParaInput.html", null ],
      [ "UI::Text", "classUI_1_1Text.html", null ],
      [ "UI::TextureViewer", "classUI_1_1TextureViewer.html", null ]
    ] ],
    [ "ImguiLayer", "classImguiLayer.html", [
      [ "MaterialViewer", "classMaterialViewer.html", null ],
      [ "Outliner", "classOutliner.html", null ],
      [ "ParamControl", "classParamControl.html", null ],
      [ "RenderConfigViewer", "classRenderConfigViewer.html", null ],
      [ "ShaderEditor", "classShaderEditor.html", null ],
      [ "TransformPanel", "classTransformPanel.html", null ],
      [ "Viewport", "classViewport.html", null ]
    ] ],
    [ "ImguiManager", "classImguiManager.html", null ],
    [ "ImguiMenu", "classImguiMenu.html", null ],
    [ "ImguiMenuItem", "classImguiMenuItem.html", [
      [ "UI::ImguiMButton", "classUI_1_1ImguiMButton.html", null ],
      [ "UI::ImguiMOption", "classUI_1_1ImguiMOption.html", null ],
      [ "UI::ImguiMSwitch", "classUI_1_1ImguiMSwitch.html", null ]
    ] ],
    [ "ImguiNodes", "structImguiNodes.html", null ],
    [ "ImguiTheme", "classImguiTheme.html", [
      [ "Outliner", "classOutliner.html", null ]
    ] ],
    [ "Input", "classInput.html", null ],
    [ "Input::InputState", "structInput_1_1InputState.html", null ],
    [ "KeyClickEvent", "structKeyClickEvent.html", null ],
    [ "KeyLeaveEvent", "structKeyLeaveEvent.html", null ],
    [ "Input::KeyState", "structInput_1_1KeyState.html", null ],
    [ "TextEditor::LanguageDefinition", "structTextEditor_1_1LanguageDefinition.html", null ],
    [ "Material", "classMaterial.html", null ],
    [ "MaterialColorChangedEvent", "structMaterialColorChangedEvent.html", null ],
    [ "MaterialFloatChangedEvent", "structMaterialFloatChangedEvent.html", null ],
    [ "MaterialNameChangedEvent", "structMaterialNameChangedEvent.html", null ],
    [ "MaterialParamEdit", "structMaterialParamEdit.html", null ],
    [ "MaterialStructChangedEvent", "structMaterialStructChangedEvent.html", null ],
    [ "MaterialTextureNameChangedEvent", "structMaterialTextureNameChangedEvent.html", null ],
    [ "MaterialTypeChangedEvent", "structMaterialTypeChangedEvent.html", null ],
    [ "MeshData", "classMeshData.html", null ],
    [ "MeshLib", "classMeshLib.html", null ],
    [ "ShaderEditor::MiniPropPanel", "structShaderEditor_1_1MiniPropPanel.html", null ],
    [ "MouseClickEvent", "structMouseClickEvent.html", null ],
    [ "MouseDragEvent", "structMouseDragEvent.html", null ],
    [ "MouseLeaveEvent", "structMouseLeaveEvent.html", null ],
    [ "MouseScrolledEvent", "structMouseScrolledEvent.html", null ],
    [ "Input::MouseState", "structInput_1_1MouseState.html", null ],
    [ "ObjectSelectedEvent", "structObjectSelectedEvent.html", null ],
    [ "Parameters::ParaData", "structParameters_1_1ParaData.html", null ],
    [ "Parameters", "classParameters.html", null ],
    [ "PinStates", "structPinStates.html", null ],
    [ "ShadowSystem::PointStruct", "structShadowSystem_1_1PointStruct.html", null ],
    [ "ShadowSystem::PolyStruct", "structShadowSystem_1_1PolyStruct.html", null ],
    [ "ShadowSystem::PolyVertStruct", "structShadowSystem_1_1PolyVertStruct.html", null ],
    [ "Input::RandomState", "structInput_1_1RandomState.html", null ],
    [ "RenderBuffer", "classRenderBuffer.html", null ],
    [ "RenderConfigChangedEvent", "structRenderConfigChangedEvent.html", null ],
    [ "RenderConfigs", "classRenderConfigs.html", null ],
    [ "RenderContext", "classRenderContext.html", null ],
    [ "Renderer", "classRenderer.html", null ],
    [ "RenderSurfaceResizedEvent", "structRenderSurfaceResizedEvent.html", null ],
    [ "SceneContext", "classSceneContext.html", null ],
    [ "ShadowSystem::SceneInfo", "structShadowSystem_1_1SceneInfo.html", null ],
    [ "SceneManager", "classSceneManager.html", null ],
    [ "SelectionChangedEvent", "structSelectionChangedEvent.html", null ],
    [ "SelectionManager< _Base >", "classSelectionManager.html", null ],
    [ "SelectionManager< ObjectID >", "classSelectionManager.html", null ],
    [ "ShaderChangedEvent", "structShaderChangedEvent.html", null ],
    [ "ShaderCodeCompileEvent", "structShaderCodeCompileEvent.html", null ],
    [ "ShaderLib", "classShaderLib.html", null ],
    [ "ShaderNodeCompileEvent", "structShaderNodeCompileEvent.html", null ],
    [ "Shaders::ShaderPair", "structShaders_1_1ShaderPair.html", null ],
    [ "Shaders", "classShaders.html", [
      [ "ChainedShader", "classChainedShader.html", null ],
      [ "ComputeShader", "classComputeShader.html", null ],
      [ "FastLoadShader", "classFastLoadShader.html", null ],
      [ "RenderShader", "classRenderShader.html", null ]
    ] ],
    [ "ShaderSaveEvent", "structShaderSaveEvent.html", null ],
    [ "ShaderStruct", "classShaderStruct.html", null ],
    [ "ShaderStructAddArrayBufferEvent", "structShaderStructAddArrayBufferEvent.html", null ],
    [ "ShaderStructAddInputEvent", "structShaderStructAddInputEvent.html", null ],
    [ "ShaderStructAddOutputEvent", "structShaderStructAddOutputEvent.html", null ],
    [ "ShaderStructAddPassEvent", "structShaderStructAddPassEvent.html", null ],
    [ "ShaderStructAddStructEvent", "structShaderStructAddStructEvent.html", null ],
    [ "ShaderStructAddUniformEvent", "structShaderStructAddUniformEvent.html", null ],
    [ "ShaderStructCompileEvent", "structShaderStructCompileEvent.html", null ],
    [ "Shaders::ShaderUnit", "classShaders_1_1ShaderUnit.html", null ],
    [ "ShadowSystem", "structShadowSystem.html", null ],
    [ "ShadowSystem::SpotStruct", "structShadowSystem_1_1SpotStruct.html", null ],
    [ "ShadowSystem::SunStruct", "structShadowSystem_1_1SunStruct.html", null ],
    [ "TextEditor", "classTextEditor.html", null ],
    [ "Texture", "classTexture.html", null ],
    [ "TextureLib", "classTextureLib.html", null ],
    [ "ThemeData", "structThemeData.html", null ],
    [ "Timer", "structTimer.html", null ],
    [ "Transform", "classTransform.html", [
      [ "Transform2D", "classTransform2D.html", [
        [ "NodeEditor", "classNodeEditor.html", null ],
        [ "Nodes", "classNodes.html", null ]
      ] ],
      [ "Transform3D", "classTransform3D.html", [
        [ "Camera", "classCamera.html", null ],
        [ "DebugLine", "classDebugLine.html", null ],
        [ "DebugPoints", "classDebugPoints.html", null ],
        [ "Empty", "classEmpty.html", null ],
        [ "Environment", "classEnvironment.html", null ],
        [ "Field", "classField.html", null ],
        [ "ImagePlane", "classImagePlane.html", null ],
        [ "Light", "classLight.html", null ],
        [ "Mesh", "classMesh.html", null ],
        [ "PolygonLight", "classPolygonLight.html", null ],
        [ "SDFField", "classSDFField.html", null ]
      ] ]
    ] ],
    [ "std::true_type", null, [
      [ "is_not_vector< T >", "structis__not__vector.html", null ]
    ] ],
    [ "UID", "classUID.html", [
      [ "ObjectID", "classObjectID.html", [
        [ "Camera", "classCamera.html", null ],
        [ "DebugLine", "classDebugLine.html", null ],
        [ "DebugPoints", "classDebugPoints.html", null ],
        [ "Empty", "classEmpty.html", null ],
        [ "Environment", "classEnvironment.html", null ],
        [ "ImagePlane", "classImagePlane.html", null ],
        [ "Light", "classLight.html", null ],
        [ "Mesh", "classMesh.html", null ],
        [ "PolygonLight", "classPolygonLight.html", null ],
        [ "PostProcessing", "classPostProcessing.html", null ],
        [ "SDFField", "classSDFField.html", null ],
        [ "Sprite", "classSprite.html", null ]
      ] ],
      [ "Scene", "classScene.html", null ]
    ] ],
    [ "VertexArray", "classVertexArray.html", null ],
    [ "MeshData::VertexIdx", "structMeshData_1_1VertexIdx.html", null ],
    [ "ViewportImageResetEvent", "structViewportImageResetEvent.html", null ],
    [ "ViewportResizeEvent", "structViewportResizeEvent.html", null ],
    [ "ViewportSelectedEvent", "structViewportSelectedEvent.html", null ]
];