site_name: OpenGL Renderer
site_description: Modern C++ Rendering Engine with OpenGL 4.6
site_url: https://xdzzzzzzyq.github.io/OpengL/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - content.code.copy

markdown_extensions:
  - pymdownx.superfences

nav:
  - Home: index.md
  - Features: features.md
  - Release: release.md
  - Developer Handbook:
    - Overview: handbook/index.md
    - Architecture: handbook/architecture.md
    - Renderer Layer: handbook/renderer.md
    - Editor Layer: handbook/editor.md
  - API Reference: Renderer\classes

plugins:
  - search
  - mkdoxy:
      projects:
        Renderer:    # name of project must be alphanumeric + numbers (without spaces)
          src-dirs: src/    # path to source code (support multiple paths separated by space) => INPUT
          full-doc: True    # if you want to generate full documentation
          doxy-cfg:         # standard doxygen configuration (key: value)
            FILE_PATTERNS: "*.cpp *.h*" # specify file patterns to filter out
            EXCLUDE_PATTERNS: "TextEditor.*" # specify patterns to exclude"
            RECURSIVE: True # recursive search in source directories
            GENERATE_XML: True
            EXTRACT_ALL: True
            EXTRACT_PRIVATE: True
            EXTRACT_STATIC: True
  - macros:
        module_name: docs/macros