#version 460 core

layout(local_size_x = 4, local_size_y = 4, local_size_z = 1) in;

layout(rgba16f, binding = 0) uniform image2D U_combine;
layout(rgba16f, binding = 1) uniform image2D U_dir_diff;
layout(rgba16f, binding = 2) uniform image2D U_dir_spec;
layout(rgba16f, binding = 3) uniform image2D U_ind_diff;
layout(rgba16f, binding = 4) uniform image2D U_ind_spec;
layout(rgba16f, binding = 5) uniform image2D U_dir_emis;


void main(){


}