
//Example code of compute summed area tables (SAT) from OpenGL Superbible, Chapter 10
//Check this book out -> https://books.google.fr/books/about/OpenGL_Superbible.html?id=Nwo0CgAAQBAJ&redir_esc=y

#version 430 core

layout(local_size_x = 256) in;
layout(rgba32f, binding = 0) uniform readonly  imageCube src;
layout(rgba32f, binding = 1) uniform writeonly imageCube dst;

shared vec4 shared_data[gl_WorkGroupSize.x * 2];

void main(void)
{
	uint id = gl_LocalInvocationID.x;
	uint rd_id;
	uint wr_id;
	uint mask;
	ivec3 P = ivec3(id * 2, gl_WorkGroupID.xy);
	const uint steps = uint(log2(gl_WorkGroupSize.x)) + 1;
	uint step = 0;
	shared_data[id * 2] =		vec4(imageLoad(src, P).rgba);
	shared_data[id * 2 + 1] =	vec4(imageLoad(src, P + ivec3(1, 0, 0)).rgba);

	barrier();

	for (step = 0; step < steps; step++)
	{
		mask = (1 << step) - 1;
		rd_id = ((id >> step) << (step + 1)) + mask;
		wr_id = rd_id + 1 + (id & mask);
		shared_data[wr_id] += shared_data[rd_id];
	
		barrier();
	}

	imageStore(dst, P.yxz,					vec4(shared_data[id * 2]));
	imageStore(dst, P.yxz + ivec3(0, 1, 0), vec4(shared_data[id * 2 + 1]));
}