name: Deploy Web Doc

on:
  push:
    branches: [ master, web-document ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Doxygen
      run: sudo apt install doxygen graphviz

    - name: Install Python deps
      run: |
        pip install mkdocs mkdocs-material mkdocstrings mkdocstrings-python mkdoxy mkdocs-macros-plugin
    - name: Generate Docs
      run: mkdocs build

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./site

    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v4